In [1]:
2**1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [2]:
import numpy as np

In [3]:
np.int64(2)**8

256

In [4]:
np.int64(2)**100

0

In [5]:
np.int64(2)**1000

0

In [6]:
2.dtype

SyntaxError: invalid syntax (<ipython-input-6-782f723ba1ea>, line 1)

In [7]:
x=2

In [8]:
x.dtype

AttributeError: 'int' object has no attribute 'dtype'

In [9]:
clear


In [10]:
arr = np.array([1,2,3])

In [11]:
type(arr)

numpy.ndarray

In [12]:
type(arr(0))

TypeError: 'numpy.ndarray' object is not callable

In [13]:
type(arr(1))

TypeError: 'numpy.ndarray' object is not callable

In [14]:
type(arr[0])

numpy.int32

In [15]:
arr*arr

array([1, 4, 9])

In [16]:
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)

In [17]:
%time v1*v2

Wall time: 31 ms


array([ 0.09951606,  0.08144078,  0.56937164, ...,  0.00096692,
        0.11835673,  0.14118115])

In [18]:
np.dot(arr,arr)

14

In [19]:
arr @ arr

14

In [20]:
v= np.arange(12)


In [21]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
v.shape

(12,)

In [23]:
mat = np.arange(12).reshape(4,3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
mat.shape

(4, 3)

In [25]:
mat.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [26]:
arr[1:,2:]

IndexError: too many indices for array

In [27]:
arr

array([1, 2, 3])

In [28]:
arr = np.arange(12).reshape(3,4)

In [29]:
arr[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [30]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
arr[:1]

array([[0, 1, 2, 3]])

In [32]:
arr[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
arr[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [34]:
arr2 = arange(12)
arr2

NameError: name 'arange' is not defined

In [35]:
arr2=np.arange(12)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
arr2[2:3]

array([2])