In [1]:
2**1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [2]:
import numpy as np

In [3]:
np.int64(2)**8

256

In [4]:
np.int64(2)**100

0

In [5]:
np.int64(2)**1000

0

In [6]:
x=2

In [7]:
arr = np.array([1,2,3])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(arr[0])

numpy.int32

In [10]:
arr*arr

array([1, 4, 9])

In [11]:
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)

In [12]:
%time v1*v2

Wall time: 8.01 ms


array([0.2105786 , 0.42156985, 0.1005367 , ..., 0.07572742, 0.0024783 ,
       0.32573268])

In [13]:
np.dot(arr,arr)

14

In [14]:
arr @ arr

14

In [15]:
v= np.arange(12)


In [16]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
v.shape

(12,)

In [18]:
mat = np.arange(12).reshape(4,3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
mat.shape

(4, 3)

In [20]:
mat.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [21]:
mat[1,:]

array([3, 4, 5])

In [22]:
mat[1:,2:]=7

In [23]:
mat


array([[ 0,  1,  2],
       [ 3,  4,  7],
       [ 6,  7,  7],
       [ 9, 10,  7]])

In [24]:
mat[1:,1:]

array([[ 4,  7],
       [ 7,  7],
       [10,  7]])

In [25]:
mat[1:,:]

array([[ 3,  4,  7],
       [ 6,  7,  7],
       [ 9, 10,  7]])

In [26]:
mat[1:,1]

array([ 4,  7, 10])

In [28]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## For every row, take the second and the third elements
The first colon in row position represents "Take all elements in the row".

The column position represents a sliced index. 1:3 represents the second and third elements. Note that the fourth element at the index position 3 is not considered, as in python.

In [36]:
arr[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

## For every row, take every element from third element till last
As in the example above only giving a colon : symbol means all elements for the row or column

In [43]:
arr[2:,:]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### For every row take every element form third element till last and same for every column.
The elements selected are a common subset. Since this is a 4X4 array, the elements 10, 11, 14 and 15 are selected.

In [44]:
arr[2:,2:]

array([[10, 11],
       [14, 15]])

Assigning a single element to parts of an array is called broadcasting. This is a common technique used to normalise parts of an array.

In [48]:
arr[2:,2:] = 0
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9,  0,  0],
       [12, 13,  0,  0]])

# Boolean Indexing

In [58]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
arr >7

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [60]:
arr[arr>7]

array([ 8,  9, 10, 11])

In [61]:
arr[(arr>2)&(arr<7)]

array([3, 4, 5, 6])

In [64]:
arr[(arr<2)|(arr>7)]

array([ 0,  1,  8,  9, 10, 11])

In [65]:
arr[~(arr >5)]

array([0, 1, 2, 3, 4, 5])

In [66]:
arr.mean()

5.5

In [67]:
arr.std()

3.452052529534663

# Broadcasting

In [68]:
ar = np.arange(3)

In [69]:
ar

array([0, 1, 2])

Multiplying two elements will multiply corresponding elements in position not give a dot product.

In [78]:
ar * ar

array([0, 1, 4])

In [79]:
ar **2

array([0, 1, 4], dtype=int32)

In [80]:
ar /7

array([0.        , 0.14285714, 0.28571429])

In [81]:
ar +4

array([4, 5, 6])

In [82]:
v1 = np.arange(3).reshape(3,1)
v1

array([[0],
       [1],
       [2]])

## Numpy will extend the vectors whenever there is a addition required.
Here we used a column vector and added it to a single row array of value \[0,1,2\]
So numpy took the vector and extended the missing elements for each element in the row of ar.
* So first element in the first row was 0, and as a result numpy added zero to each element of the vector. So we get original values in first column
* The second element in the first row was 1, and as a result numpy added 1 to each element of the vector so we get \[\[1,2,3\]\] as the column.

In [83]:
ar + v1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Array operations

In [85]:
v = np.arange(9).reshape(3,3)
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

A quick way to find if any zero elements exist in the array.

In [87]:
v.prod()

0

Generally the functions will give the result for the entire array or matrix.

In [89]:
v.sum()

36

But if we mention the axis, we will get a new array with row or column wise computation. axis = 0 means columns wise computation. axis = 1 means row wise computation for a 2D matrix.

In [92]:
v.sum(axis=0)

array([ 9, 12, 15])

In [93]:
v2 = v.copy()

In [94]:
v2[1,1] = 100

In [96]:
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [97]:
v2

array([[  0,   1,   2],
       [  3, 100,   5],
       [  6,   7,   8]])

### Dumping and loading data to and from arrays.
The dumps() and loads() methods use the pickle protocol of python.

In [98]:
data = v.dumps()

In [99]:
data

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x03K\x03\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i4q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X$\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [100]:
v3 = np.loads(data)
v3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Ufuncs are universal functions in numpy
The reason numpy redefined common functions already available in python libraires is becasue ufuncs can take scalars and vectors and NaN values as well. We can use